table customer_data_cleaned
	lineageTag: 50a5068f-f4ac-41da-94b5-5aab9946d417
	sourceLineageTag: [dbo].[customer_data_cleaned]

	measure 'Total Customers' = ```
			COUNTROWS(customer_data_cleaned)
			
			```
		formatString: 0
		lineageTag: 5808bd91-a351-4141-b3f5-c909f82bd236

		changedProperty = Name

	measure sum_Income = ```
			sum(customer_data_cleaned[income_clean])
			
			```
		lineageTag: f601f375-88e3-4263-bcdc-a14b34bc2bd1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Bucket Group' =
			
			SWITCH(
			    TRUE(),
			    [sum_Income] < 20000, "<20k",
			    [sum_Income] < 50000, "20k–50k",
			    [sum_Income] < 100000, "50k–100k",
			    "100k+"
			)
		lineageTag: fd410b20-9834-45e4-8e80-d93f6141fc56

		changedProperty = Name

	measure Income_Post_Tax = divide([sum_Income], 15.75, 0)
		lineageTag: 3370b7e0-ce8b-409d-b89d-9153b52a4661

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure customercount = CALCULATE(DISTINCTCOUNT(customer_data_cleaned[customer_id]))
		formatString: 0
		lineageTag: 5445532a-23ba-4ca0-945b-684a236ca9fb

		changedProperty = Name

	measure 'average Income' = AVERAGE(customer_data_cleaned[income_clean])
		lineageTag: 8c367979-91d2-4c30-b4df-efde8daa96f0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure sum_age = sum(customer_data_cleaned[age_clean])
		lineageTag: 3e00d5e9-4cbf-4038-a60f-4e850669067b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'valid_signup %' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER(customer_data_cleaned, NOT (ISBLANK(customer_data_cleaned[signup_date_parsed])))),
			    COUNTROWS(customer_data_cleaned)
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 95351f98-efae-46c9-b242-04c7fb6c7917

	measure 12_month_rolling_signups = ```
			
			CALCULATE(
			    COUNT(customer_data_cleaned[customer_id]),
			    DATESINPERIOD(customer_data_cleaned[signup_date_parsed], MAX(customer_data_cleaned[signup_date_parsed]), -12, MONTH)
			)
			
			```
		lineageTag: 8480d9c8-5d06-48c2-b8ba-55396df50f24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Signup Color' = ```
			
			SWITCH(
			    TRUE(),
			    [valid_signup %] >= 0.95, "#2ECC71",  // Green
			    [valid_signup %] >= 0.85, "#F1C40F",  // Yellow
			    "#E74C3C"                             // Red
			)
			
			```
		lineageTag: 734189b9-b21e-4ed4-bee0-ac68c3ec13d1

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average age' = AVERAGE(customer_data_cleaned[age_clean])
		lineageTag: f48f35d2-16ab-4770-889a-ad028c97dcf0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'average age color' =
			
			SWITCH(
			    TRUE(),
			    [average age] >= 80, "#E74C3C",  // Red
			    [average age] >= 70, "#E74C1A",  // Yellow
			    [average age] >= 60, "#E74C00",  // Yellow
			    [average age] >= 50, "#F1C40F",  // Yellow
			    [average age] >= 40, "#F1C40F",  // Yellow
			    [average age] >= 30, "#2ECC11",  // Yellow
			      "#2ECC71"                           // Green
			)
		lineageTag: 620fbdac-1455-4390-9639-2c5abe898a81

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: string
		lineageTag: a91b8ca8-565b-41fc-bdc2-6efe9500faaf
		sourceLineageTag: customer_id
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 6fea2fc9-db4a-4344-929d-e89a535306e0
		sourceLineageTag: email
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column signup_date_parsed
		dataType: dateTime
		formatString: Short Date
		lineageTag: 756c5bec-f0f6-45f1-a210-7a151a7a226c
		sourceLineageTag: signup_date_parsed
		summarizeBy: none
		sourceColumn: signup_date_parsed

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column age_clean
		dataType: int64
		formatString: 0
		lineageTag: 88ee4290-6b1f-458e-a0c0-17ebd7b94d27
		sourceLineageTag: age_clean
		summarizeBy: sum
		sourceColumn: age_clean

		annotation SummarizationSetBy = Automatic

	column income_clean
		dataType: double
		lineageTag: 46711115-b197-4727-b281-1b5205d17014
		sourceLineageTag: income_clean
		summarizeBy: sum
		sourceColumn: income_clean

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column referral_code
		dataType: string
		lineageTag: 1291aaf9-1d56-48fc-adc6-1ac5429490d0
		sourceLineageTag: referral_code
		summarizeBy: none
		sourceColumn: referral_code

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: e4986dde-0ccd-48ec-92b4-8668bce09c17
		sourceLineageTag: country_code
		dataCategory: Country
		summarizeBy: none
		sourceColumn: country_code

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column phone_number
		dataType: string
		lineageTag: 197cd84e-a069-42fb-b6cd-21a01abe3bdd
		sourceLineageTag: phone_number
		summarizeBy: none
		sourceColumn: phone_number

		annotation SummarizationSetBy = Automatic

	column subscription_type
		dataType: string
		lineageTag: 21569cb0-da6c-47ee-bd05-ea10812ebec2
		sourceLineageTag: subscription_type
		summarizeBy: none
		sourceColumn: subscription_type

		annotation SummarizationSetBy = Automatic

	column last_login
		dataType: string
		lineageTag: 50e6a328-4c2a-46bb-aebf-545eb78bd6fb
		sourceLineageTag: last_login
		summarizeBy: none
		sourceColumn: last_login

		annotation SummarizationSetBy = Automatic

	column income_bin
		dataType: string
		lineageTag: 914f7c78-3a68-4cae-971b-b6ff692844f6
		sourceLineageTag: income_bin
		summarizeBy: none
		sourceColumn: income_bin

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 67e94b88-32bc-4405-b87f-246a7d718a95
		sourceLineageTag: Month
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 3bf34772-ffad-4ee7-8fae-c3eacdb922bf
		sourceLineageTag: Quarter
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 683b11e1-84d7-407d-8ed4-137703f276f2
		sourceLineageTag: Day
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 7862d2dd-9ae8-4be4-b7a1-e1ebb464ab7d
		sourceLineageTag: Year
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 5f015e7e-c147-430d-9565-0ff5c3fd6b01
		sourceLineageTag: FiscalYear
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonth
		dataType: int64
		formatString: 0
		lineageTag: fdd6f9d1-4a71-41b2-922a-08f0660f6736
		sourceLineageTag: FiscalMonth
		summarizeBy: sum
		sourceColumn: FiscalMonth

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: string
		lineageTag: ee93ca42-2dbe-4244-be7b-d7f4f71e68b0
		sourceLineageTag: FiscalQuarter
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column Age_group
		dataType: string
		lineageTag: c88c305e-fc18-4616-ad76-7f353ec67370
		sourceLineageTag: Age_group
		summarizeBy: none
		sourceColumn: Age_group
		sortByColumn: Age_group_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column HolidayDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9d84183c-1139-40ee-a078-e630237a1289
		sourceLineageTag: HolidayDate
		summarizeBy: none
		sourceColumn: HolidayDate

		annotation SummarizationSetBy = Automatic

	column IsUKHoliday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9565f454-9022-483e-a775-4a384c7d6cc0
		sourceLineageTag: IsUKHoliday
		summarizeBy: none
		sourceColumn: IsUKHoliday

		annotation SummarizationSetBy = Automatic

	column Age_group_sort
		dataType: int64
		formatString: 0
		lineageTag: cd06946d-a663-4ccf-8fe3-947943773fb5
		sourceLineageTag: Age_group_sort
		summarizeBy: none
		sourceColumn: Age_group_sort

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	partition customer_data_cleaned = entity
		mode: directLake
		source
			entityName: customer_data_cleaned
			expressionSource: 'DirectLake - laserengravelakehouse'

